name: Build npm release

trigger:
  batch: true
  branches:
    include:
      - master
      - refs/tags/*

jobs:
  - template: .ci/build-platform.yml
    parameters:
      platform: macOS
      vmImage: macOS-latest
      STAGING_DIRECTORY: /Users/vsts/STAGING
      STAGING_DIRECTORY_UNIX: /Users/vsts/STAGING
      ESY__CACHE_INSTALL_PATH: /Users/vsts/.esy/3____________________________________________________________________/i
      ESY__CACHE_SOURCE_TARBALL_PATH: /Users/vsts/.esy/source/i

  - job: Release
    displayName: Publish release
    condition: startsWith(variables['build.sourceBranch'], 'refs/tags/')
    dependsOn: macOS
      #- Linux
      #- Windows
    pool:
      vmImage: macOS-latest
      demands: node.js
    steps:
      - template: .ci/cross-release.yml
      - task: Npm@1
        inputs:
          command: publish
          workingDir: "_release"
          publishEndpoint: NPM

